// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemberSnapshot = { member_user_id: string, member_name: string, project_ids: Array<string>, bluf_markdown: string, last_update_at: string, };
