// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberSnapshot } from "./MemberSnapshot";
import type { ProjectBlufSnapshot } from "./ProjectBlufSnapshot";

export type OrganizationSnapshot = { bluf_markdown: string, projects: Array<ProjectBlufSnapshot>, members: Array<MemberSnapshot>, };
