// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmployeeSnapshot } from "./EmployeeSnapshot";

export type RoomSnapshot = { bluf_markdown: string, detailed_summary_markdown: string, employees: Array<EmployeeSnapshot>, };
