// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HookTurnReport = { client: string, repo_root: string, branch: string | null, payload: unknown, };
