// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UploadedTranscript = { session_id: string, transcript_path: string, content_text: string, };
