// Auto-generated by ts-rs from Rust updates protocol types — do not edit manually.
// Re-run `cargo test -p reporter-protocol` to regenerate.
export type { Update } from "./Update";
export type { UpdateScope } from "./UpdateScope";
