// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateScope } from "./UpdateScope";

export type Update = { seq: number, update_id: string, organization_id: string, scope: UpdateScope, project_id: string | null, member_user_id: string | null, body_text: string, source_workflow_kind: string, created_at: string, };
